name: Unit Tests

on: [push]

defaults:
    run:
        shell: bash
        working-directory: .

jobs:
    run_unit_tests:
        name: Run Unit Tests
        runs-on: ubuntu-latest
        container: epitechcontent/epitest-docker:latest

        steps:
          - uses: actions/checkout@v2
          - name: Build
            run: make tests_run
          - name: Run
            run: ./unit_test -j1 --verbose